import type { Metadata } from 'next';
import './globals.css';
import LayoutProvider from './components/providers/LayoutProvider';
import { Kalam, Karla } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const kalam = Kalam({
    subsets: ['latin'],
    weight: ['300', '400', '700'],
    variable: '--font-kalam'
});

const karla = Karla({
    subsets: ['latin'],
    variable: '--font-karla'
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: 'public/image/logo2.png'
    }
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${karla.variable} ${kalam.variable} antialiased`}>
                <LayoutProvider>
                    {children}
                    <Toaster
                        position="bottom-center"
                        containerStyle={{
                            zIndex: 999999
                        }}
                    />
                    ;
                </LayoutProvider>
            </body>
        </html>
    );
}
